import type { MessageSchema } from '../schema'

const messages: MessageSchema = {
  common: { language: 'Language', logout: 'Sign out', account: 'Account', loading: 'Loading', loadFailed: 'Data failed to load', retry: 'Retry', empty: 'No data yet', save: 'Save', yes: 'Yes', no: 'No' },
  errors: { usernameInvalid: 'Username must contain 3-64 letters, numbers, dots, underscores, or hyphens', usernameConflict: 'Username already exists', passwordPolicy: 'Password does not meet the security policy', currentPassword: 'Current password is incorrect', adminProtected: 'This operation cannot target an administrator account', accountDeleted: 'Account is deleted', accountStatus: 'Invalid account status filter', unknown: 'Operation failed. Please try again.' },
  navigation: { dashboard: 'Overview', agents: 'Agents', routes: 'Managed routes', tunnels: 'Tunnels', tokens: 'Access tokens', servers: 'Server nodes', audits: 'Audit logs', users: 'Child accounts', security: 'Security' },
  shell: { console: 'Network console', collapse: 'Collapse navigation', expand: 'Expand navigation' },
  servers: { title: 'Server nodes', description: 'Monitor cluster Server health, load, and lifecycle', refresh: 'Refresh', selfRegister: 'Servers self-register after node identity initialization. Disable and delete are logical operations and can be restored.', empty: 'No Server nodes yet', name: 'Name', id: 'Node ID', address: 'Relay address', epoch: 'Epoch', statusLabel: 'Status', activeConnections: 'Active connections', activeStreams: 'Active streams', healthScore: 'Health score', lastSeen: 'Last heartbeat', leaseExpires: 'Lease expires', actions: 'Actions', detail: 'Details', detailTitle: 'Server node details', enabled: 'Enabled', deletedAt: 'Deleted at', createdAt: 'Created', updatedAt: 'Updated', enable: 'Enable', disable: 'Disable', delete: 'Delete', restore: 'Restore', loadMore: 'Load more', enabledMessage: 'Server node enabled', disabledMessage: 'Server node disabled', deletedMessage: 'Server node logically deleted', restoredMessage: 'Server node restored', deleteTitle: 'Delete Server node', deleteConfirm: 'Deleting disables the node while retaining its record for restoration. Continue?', operationFailed: 'Operation failed', status: { online: 'Online', offline: 'Offline', disabled: 'Disabled', deleted: 'Deleted' } },
  users: { title: 'Child accounts', description: 'Create and manage ordinary accounts', create: 'Add account', username: 'Username', status: 'Status', active: 'Active', disabled: 'Disabled', deleted: 'Deleted', all: 'All', createdAt: 'Created', actions: 'Actions', enable: 'Enable', disable: 'Disable', resetPassword: 'Reset password', delete: 'Delete', restore: 'Restore', cancel: 'Cancel', temporaryPassword: 'One-time temporary password', passwordWarning: 'This password is shown once. Store it securely now.', copy: 'Copy', copied: 'Copied', done: 'Done', loadFailed: 'Could not load accounts', operationFailed: 'Operation failed', created: 'Account created', restored: 'Account restored', confirmEnable: 'Enable this account?', confirmDisable: 'Disabling blocks this account’s tokens. Continue?', confirmReset: 'Reset this password? Existing login tokens remain valid.', confirmDelete: 'Deleting disables the account but retains its resources. Continue?' },
  security: { title: 'Security', description: 'Change the current account password', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', save: 'Save changes', length: 'Use 12–128 characters', mismatch: 'The new passwords do not match', saved: 'Password changed. Your current session remains active.', failed: 'Password change failed' },
  auth: { welcome: 'Sign in to TunnelMesh', description: 'Open the network and tunnel management console', username: 'Username', password: 'Password', signIn: 'Sign in', failed: 'Invalid username or password' },
  dashboard: { title: 'Operations overview', description: 'Live resource summary within your access scope', retry: 'Retry', unavailable: 'Summary unavailable. Try again.', agents: 'Agents', online: 'Online agents', tunnels: 'Active tunnels', routes: 'Managed routes', tokens: 'Valid tokens', recentEvents: 'Recent events', noEvents: 'No recent events' },
  agents: { title: 'Agents', name: 'Name', status: 'Status', actions: 'Actions', details: 'Details', active: 'Active', disabled: 'Disabled', create: 'Create agent', created: 'Agent created', createFailed: 'Could not create agent', nameRequired: 'Enter an agent name' },
  routes: { title: 'Managed routes', description: 'Manage explicit subdomains and dynamic domain routes', create: 'Add managed route', edit: 'Edit', editTitle: 'Edit managed route', empty: 'No managed routes yet', domain: 'Domain', domainHelp: 'Use an exact domain or a single-level tm-* wildcard, for example tm-git.claw.qihoo.net', path: 'Path', agent: 'Agent', protocol: 'Protocol', target: 'Target', targetHost: 'Target host', targetHostHelp: 'Use an IP or hostname; the Agent connects from its own network', targetPort: 'Target port', targetScheme: 'Upstream scheme', targetSchemeHelp: 'HTTP uses a plaintext connection; HTTPS uses TLS from the Agent to the target', hostHeader: 'Upstream Host', hostHeaderHelp: 'Leave empty to use the target host; useful for virtual-host services', tlsServerName: 'TLS server name', tlsServerNameHelp: 'Leave empty to use the target host; used for SNI and certificate verification, which cannot be skipped', status: 'Status', active: 'Active', disabled: 'Disabled', actions: 'Actions', searchAgents: 'Search by name or ID', agentLoadFailed: 'Could not load agents', agentRequired: 'Select an agent', domainRequired: 'Enter a domain', targetRequired: 'Enter a target host', cancel: 'Cancel', created: 'Route created', createFailed: 'Could not create route', updated: 'Route updated; it takes effect within 5 seconds', updateFailed: 'Could not update route' },
  tunnels: { title: 'Tunnels', protocol: 'Protocol', target: 'Target', status: 'Status' },
  audits: { title: 'Audit logs', description: 'Review the actor, resource, and details of management operations', time: 'Time', timeRange: 'Time range', actor: 'Actor', action: 'Action', resourceType: 'Resource type', resourceId: 'Resource ID', actions: 'Actions', detail: 'Details', detailTitle: 'Audit details', emptyDetails: 'No additional details', reset: 'Reset', query: 'Search' },
  agentDetail: { title: 'Agent details', metadata: 'Metadata', stale: 'Stale', fresh: 'Fresh', instanceId: 'Instance ID', nodeId: 'Node ID', epoch: 'Epoch', revision: 'Revision', status: 'Status', activeInstances: 'Active instances', activeConnections: 'Active connections', connectionCount: 'Connections', instances: 'Instances', connections: 'Connections', connectionId: 'Connection ID', connectionEpoch: 'Connection epoch', serverNodeId: 'Server node', serverNodeAddress: 'Server address', healthy: 'Healthy', unhealthy: 'Unhealthy', activeStreams: 'Active streams', lastHeartbeatAt: 'Last heartbeat', leaseExpiresAt: 'Lease expires', actions: 'Actions', close: 'Close', closeTitle: 'Close physical connection', cancel: 'Cancel', closeFailed: 'Could not close the connection', remoteNodeUnavailable: 'The remote Server node is unavailable. The lease was preserved; try again later.', refresh: 'Refresh', connectionsLoadFailed: 'Could not load cluster connections', reportedAt: 'Reported at', updatedAt: 'Updated at', name: 'Name', source: 'Source', value: 'Value', redacted: 'Redacted', empty: 'No metadata reported', unavailable: 'Metadata unavailable', failed: 'Could not load metadata' },
  tokens: { eyebrow: 'Credential control', title: 'Service tokens', description: 'Issue least-privilege credentials for Agents, Clients, and server-node relay. Secrets appear once.', create: 'Create token', allTypes: 'All types', agent: 'Agent', client: 'Client', serverNode: 'Server node', refresh: 'Refresh', prefix: 'Prefix', type: 'Type', owner: 'Owner', binding: 'Binding', scoped: 'Scoped', state: 'State', expires: 'Expires', lastUsed: 'Last used', actions: 'Actions', detail: 'Details', detailTitle: 'Token details', id: 'ID', scope: 'Scope', scopeUpdate: 'Update scope', scopeUpdateTitle: 'Update token scope', scopeUpdated: 'Scope updated', allProtocols: 'Leave unchecked to allow every protocol', allCIDRs: 'Leave empty to allow every target address', revokedAt: 'Revoked at', createdAt: 'Created at', updatedAt: 'Updated at', replayed: 'Idempotent replay', expiration: 'Expiration', expirationTitle: 'Update expiration', noExpiration: 'Leave empty for no expiration', expirationUpdated: 'Expiration updated', updateFailed: 'Update failed', reveal: 'Reveal', rotate: 'Rotate', revoke: 'Revoke', loadMore: 'Load more', empty: 'No service tokens yet', agentId: 'Agent ID', nodeId: 'Node ID', serverNodes: 'Server nodes', searchServerNodes: 'Search by name or ID', allServerNodes: 'Leave empty to allow every Server node', agentIds: 'Agent IDs', allAgents: 'Leave empty to allow every Agent', agentOwnerMismatch: 'A client token can only select agents from one owner', protocols: 'Protocols', cidrs: 'Target CIDRs', ports: 'Target ports', allPorts: 'Leave empty to allow every port', expiresOptional: 'Expires at (optional)', searchAgents: 'Search by name or ID', agentRequired: 'Select an agent', cancel: 'Cancel', created: 'Token created', createFailed: 'Token creation failed', rotateTitle: 'Rotate token', rotateConfirm: 'Rotating revokes the current token immediately. Continue?', rotateFailed: 'Rotate failed', revealTitle: 'Reveal token secret', revealConfirm: 'Type REVEAL to confirm this audited secret read.', revealInput: 'Enter REVEAL exactly', revealFailed: 'Reveal failed', revokeTitle: 'Revoke token', revokeConfirm: 'Revoked tokens cannot be used again. Continue?', revoked: 'Token revoked', revokeFailed: 'Revoke failed', secretTitle: 'Copy this secret now', secretWarning: 'The secret is shown once. It is not stored in the browser or returned by later requests.', copy: 'Copy', saved: 'I saved it' },
}
export default messages
