#!/usr/bin/env bash
# Package the macOS menu-bar client as "TunnelMesh Client.app" inside a disk image.
#
# The tray links Cocoa and WebKit through cgo, so it can only be built on a macOS host with
# a working Xcode command-line toolchain, while scripts/build-release.sh cross-compiles
# every other binary with CGO_ENABLED=0 from Linux. The release workflow therefore runs this
# script on a macOS runner and hands the resulting .dmg files to build-release.sh through
# TRAY_DIST_DIR (scripts/merge-tray-dist.sh), so one GitHub Release carries all eight
# assets and one SHA256SUMS covers every one of them. Keeping the two build paths apart
# means the cross-platform release never depends on a Mac, and the Mac-only artifact never
# pretends to be portable.
set -euo pipefail
export LC_ALL=C

APP_NAME="TunnelMesh Client.app"
# The mounted volume is named after the app without the .app suffix, which is what Finder
# shows in the sidebar; a volume called "tunnelmesh-client-tray-v1.2.3-darwin-arm64" would
# look like a build artifact rather than something to install.
VOLUME_NAME="TunnelMesh Client"
BUNDLE_ID="com.tunnelmesh.client-tray"
EXECUTABLE="tunnelmesh-client-tray"

VERSION="${VERSION:-dev}"
ARCHES="${ARCHES:-arm64 amd64}"
# macOS ships bash 3.2, where "${array[*]}" on an empty array is an unbound-variable
# error under `set -u` rather than an empty string. An empty ARCHES would therefore die
# at the manifest step, after both builds had already run, which is the worst place to
# find out. Reject it up front instead.
if [[ -z "${ARCHES//[[:space:]]/}" ]]; then
  echo "ARCHES must name at least one darwin architecture (arm64, amd64)" >&2
  exit 1
fi
# Ad-hoc by default: it is enough for a locally built app and for `codesign --verify`
# to mean something. A Developer ID identity plus notarization is a separate release
# step, and passing one here is all that is needed to use it.
SIGN_IDENTITY="${SIGN_IDENTITY:--}"
# ${VAR:-default} does not fire for a variable that is set but empty, and
# `codesign --sign ""` fails with a message about searching for identities rather than
# about the empty value. Normalizing here keeps SIGN_IDENTITY= meaning "ad-hoc".
if [[ -z "$SIGN_IDENTITY" ]]; then
  SIGN_IDENTITY="-"
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="${DIST_DIR:-dist/${VERSION}/macos-tray}"
if [[ "$DIST_DIR" = /* ]]; then
  OUTPUT_DIR="$DIST_DIR"
else
  OUTPUT_DIR="$ROOT_DIR/$DIST_DIR"
fi
INFO_TEMPLATE="$ROOT_DIR/deploy/macos/TunnelMeshClient-Info.plist"
ICON_SOURCE="${ICON_SOURCE:-$ROOT_DIR/deploy/macos/TunnelMeshClient.icns}"
# The menu-bar glyph is the same mark as that .icns, drawn monochrome by the same
# generator. It is a separate file because a status item cannot use an .icns: the icon is
# tinted by the system, so it has to arrive as a template image.
MENUBAR_SOURCE_DIR="${MENUBAR_SOURCE_DIR:-$ROOT_DIR/deploy/macos}"
WEB_DIST_DIR="$ROOT_DIR/internal/tray/webdist/dist"
LAYOUT_SCRIPT="$ROOT_DIR/deploy/macos/tray-dmg-layout.applescript"
# An installer window can carry a background picture. Nothing in the repository ships one,
# so the default is no background; an operator who sets DMG_BACKGROUND is asking for it. A
# path that is not a file is a typo, and a typo has to fail before two architectures have
# been compiled rather than after.
DMG_BACKGROUND="${DMG_BACKGROUND:-}"
if [[ -n "$DMG_BACKGROUND" ]]; then
  if [[ ! -f "$DMG_BACKGROUND" ]]; then
    echo "DMG_BACKGROUND is not a file: $DMG_BACKGROUND" >&2
    exit 1
  fi
  # hdiutil and Finder both resolve the picture against the mounted volume, so the path
  # handed to the layout script has to be absolute.
  DMG_BACKGROUND="$(cd "$(dirname "$DMG_BACKGROUND")" && pwd)/$(basename "$DMG_BACKGROUND")"
fi

usage() {
  cat <<USAGE
usage: VERSION=vX.Y.Z [ARCHES="arm64 amd64"] [SIGN_IDENTITY=-] [DIST_DIR=path] $0

Builds cmd/tunnelmesh-client-tray with -tags tray for each architecture, assembles
$APP_NAME, signs it and writes one .dmg per architecture next to SHA256SUMS. Each image
mounts as an installer window: the app beside an "Applications" alias, positioned so that
installing is a drag onto a visible target.

  VERSION          release version (default: dev; otherwise vMAJOR.MINOR.PATCH[-suffix])
  ARCHES           space separated darwin architectures (default: arm64 amd64)
  SIGN_IDENTITY    codesign identity (default: "-" for ad-hoc)
  DIST_DIR         output directory (default: dist/<VERSION>/macos-tray)
  ICON_SOURCE      .icns to embed (default: deploy/macos/TunnelMeshClient.icns, generated by
                   scripts/generate-tray-icon.sh; a missing file packages without one)
  MENUBAR_SOURCE_DIR  directory holding TunnelMeshMenuBar.png for the status item (default:
                   deploy/macos, written by the same generator)
  DMG_BACKGROUND   png to draw behind the icons (default: none)

Prerequisites: a macOS host, go, codesign, plutil, ditto, hdiutil, and a built front end
(cd web-tray && npm run build). The icon layout that makes the image read as an installer
is Finder state, so it is written by scripting Finder; a host where that is impossible
still produces a working image and records "installerLayout": false in the manifest.
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "the tray client links Cocoa and WebKit through cgo and can only be packaged on macOS" >&2
  exit 1
fi
if [[ "$VERSION" != "dev" && ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
  echo "VERSION must be vMAJOR.MINOR.PATCH (an optional pre-release suffix is allowed for test builds): $VERSION" >&2
  exit 1
fi
# otool is not optional: the deployment floor is only real once the built binary has been
# read back and agreed to it (verify_deployment_target).
for tool in go codesign plutil ditto hdiutil otool; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "$tool is required" >&2
    exit 1
  fi
done
if [[ ! -f "$INFO_TEMPLATE" ]]; then
  echo "missing Info.plist template: $INFO_TEMPLATE" >&2
  exit 1
fi

# The deployment floor belongs to the bundle, so the plist states it once and the build
# reads it back. It used to be a second literal in this script, which is precisely how the
# two drifted apart: manifest.json promised macOS 13 while the executable was linked for
# whatever OS the runner happened to run, and LaunchServices enforces the executable.
MIN_MACOS="$(plutil -extract LSMinimumSystemVersion raw "$INFO_TEMPLATE")"
if [[ ! "$MIN_MACOS" =~ ^[0-9]+\.[0-9]+$ ]]; then
  echo "could not read LSMinimumSystemVersion from $INFO_TEMPLATE (got: ${MIN_MACOS:-empty})" >&2
  exit 1
fi
if [[ ! -f "$LAYOUT_SCRIPT" ]]; then
  echo "missing installer layout script: $LAYOUT_SCRIPT" >&2
  exit 1
fi

# The settings interface is embedded at compile time. A clean checkout has no bundle at
# all, and a host may still hold the previous one, so refuse instead of shipping an app
# whose window renders a "run npm run build" placeholder.
if [[ ! -f "$WEB_DIST_DIR/index.html" ]]; then
  echo "internal/tray/webdist/dist/index.html is missing; run: cd web-tray && npm run build" >&2
  exit 1
fi
if [[ -f "$ROOT_DIR/web-tray/dist/index.html" ]] && ! diff -qr "$ROOT_DIR/web-tray/dist" "$WEB_DIST_DIR" >/dev/null 2>&1; then
  echo "internal/tray/webdist/dist is stale relative to web-tray/dist; run: cd web-tray && npm run build" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"
: > "$OUTPUT_DIR/SHA256SUMS"

COMMIT="$(git -C "$ROOT_DIR" rev-parse HEAD)"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
# CFBundleShortVersionString is documented as three dot-separated integers, and Finder,
# Software Update and every "what version is this" panel parse it that way. The leading
# "v" belongs to the git tag, not to the bundle, so it is dropped here and only here:
# the binary still reports the full tag through internal/build.
BUNDLE_VERSION="${VERSION#v}"
LDFLAGS="-s -w -X github.com/tunnelmesh/tunnelmesh/internal/build.Version=${VERSION} -X github.com/tunnelmesh/tunnelmesh/internal/build.Commit=${COMMIT} -X github.com/tunnelmesh/tunnelmesh/internal/build.BuildTime=${BUILD_TIME}"

checksum() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1"
  else
    shasum -a 256 "$1"
  fi
}

# retry3 runs a hdiutil command three times with a growing pause, then once more unquiet.
#
# hdiutil keeps its device around for a moment after a call, and on a shared CI runner the
# first attempt can fail with "Resource busy" for reasons that have nothing to do with the
# inputs. The last attempt is not silenced: a release must never ship without its disk
# image, and when it really does fail the cause has to reach the log.
retry3() {
  local attempt
  for attempt in 1 2 3; do
    if "$@" >/dev/null 2>&1; then
      return 0
    fi
    if [[ "$attempt" != 3 ]]; then
      sleep $((attempt * 5))
    fi
  done
  echo "failed after 3 attempts, retrying with output visible: $*" >&2
  "$@"
}

# apply_installer_layout drives Finder over a mounted read-write image.
#
# Best effort on purpose. The layout is what makes the image read as an installer, but it
# needs a Finder that can be scripted, and a release must not die because a runner had no
# window server session. A failure is reported on stderr and recorded in the manifest as
# "installerLayout": false, so a published image never claims a layout it does not have.
# Installing by drag still works without it.
apply_installer_layout() {
  local mount="$1" background="$2" attempt
  if ! command -v osascript >/dev/null 2>&1; then
    echo "warning: osascript is not installed, so the layout cannot be applied" >&2
  else
    for attempt in 1 2 3; do
      if osascript "$LAYOUT_SCRIPT" "$mount" "$APP_NAME" "$background" >/dev/null 2>&1; then
        return 0
      fi
      echo "installer layout attempt ${attempt}/3 failed" >&2
      if [[ "$attempt" != 3 ]]; then
        sleep $((attempt * 3))
      fi
    done
    echo "running the installer layout once more with its output visible" >&2
    if osascript "$LAYOUT_SCRIPT" "$mount" "$APP_NAME" "$background"; then
      return 0
    fi
  fi
  echo "warning: the installer layout could not be applied; the disk image still installs by drag but opens as a plain folder window" >&2
  return 1
}

# detach_volume releases a mounted image. Finder can hold the window for a moment after it
# has been told to close it, and converting an image that is still mounted freezes whatever
# the flush happened to reach, so -force is the last resort rather than the default.
detach_volume() {
  local mount="$1" attempt
  for attempt in 1 2 3; do
    if hdiutil detach "$mount" >/dev/null 2>&1; then
      return 0
    fi
    if [[ "$attempt" != 3 ]]; then
      sleep $((attempt * 3))
    fi
  done
  hdiutil detach "$mount" -force
}

# create_disk_image writes a compressed read-only disk image from a staged volume directory.
#
# It is two images rather than one. The layout a user recognises as an installer - an icon
# view window of a fixed size, the app above one icon position and the "Applications" alias
# above the other - is Finder state stored in .DS_Store, and only Finder writes that file.
# So hdiutil builds a read-write image, the volume is mounted at a private path,
# deploy/macos/tray-dmg-layout.applescript drives Finder over it, and the result is converted
# into the compressed image that ships. Slack a read-write image needs costs nothing there,
# because free blocks compress away.
#
# The outcome of the layout pass comes back in the global installer_layout, because the
# manifest has to state what the published image actually contains.
create_disk_image() {
  local volume="$1" output="$2"
  local work rw mount background="" size_kb size_mb
  work="$(mktemp -d)"
  rw="$work/read-write.dmg"
  mount="$work/mount"
  mkdir -p "$mount"

  # hdiutil sizes a -srcfolder image to its content plus a little slack, which is enough
  # for the copy itself but not for the .DS_Store Finder writes afterwards. Ask for the
  # content again on top of it, with a floor so a very small payload still fits.
  size_kb="$(du -sk "$volume" | awk '{print $1}')"
  size_mb=$(( (size_kb + 1023) / 1024 * 5 / 4 + 16 ))

  retry3 hdiutil create -size "${size_mb}m" -volname "$VOLUME_NAME" -srcfolder "$volume" -ov -format UDRW -fs HFS+ "$rw"
  retry3 hdiutil attach -readwrite -noverify -noautoopen -mountpoint "$mount" "$rw"
  if [[ -d "$volume/.background" ]]; then
    # A leading dot does not hide a folder from an icon view window; the hidden flag does,
    # and it is set on the mounted volume so the finished image carries it.
    chflags hidden "$mount/.background"
    background="$mount/.background/background.png"
  fi
  if apply_installer_layout "$mount" "$background"; then
    installer_layout="true"
  else
    installer_layout="false"
  fi
  # The volume carries the same tile as the app, so the disk image a user opens reads as
  # TunnelMesh rather than as an unnamed grey drive.
  #
  # This copy happens after the layout pass, not with the rest of the staging, because
  # Finder's "update volume" consumes a .VolumeIcon.icns that is already there: it applies
  # the icon and deletes the file, and the applied icon does not survive hdiutil convert.
  # Measured on this host: staged before the layout, the published image mounts as a generic
  # disk; staged after it, the mounted volume shows the brand tile.
  if [[ -f "$ICON_SOURCE" ]]; then
    cp "$ICON_SOURCE" "$mount/.VolumeIcon.icns"
    # The custom-icon flag is what tells Finder to read the file instead of the default.
    # SetFile is a command line tool binary, so a host without one still gets a usable
    # image; it only says goodbye to the volume tile.
    if command -v SetFile >/dev/null 2>&1; then
      SetFile -a C "$mount"
    else
      echo "note: SetFile is unavailable; the mounted volume keeps the system disk icon" >&2
    fi
  fi
  # Flush before detaching: the layout is the whole reason for the extra step, and an image
  # whose .DS_Store never reached the disk looks identical to one that has it.
  sync
  detach_volume "$mount"
  retry3 hdiutil convert "$rw" -format UDZO -imagekey zlib-level=9 -ov -o "$output"
  rm -rf "$work"
}

# verify_deployment_target fails the build unless the Mach-O load command agrees with the
# bundle.
#
# Passing the flag is a request; this is the proof. clang records the build host's OS
# release as LC_BUILD_VERSION minos unless told otherwise, and a macOS 15 runner shipped a
# .dmg whose app would not open on macOS 14 with "requires macOS 15.0 or later" - a
# download-level failure no test that only reads this script could ever notice. An empty
# reading is treated as a mismatch on purpose: a toolchain that stops emitting the load
# command has to stop the release rather than let the check quietly pass.
verify_deployment_target() {
  local binary="$1" recorded
  recorded="$(otool -l "$binary" | awk '/LC_BUILD_VERSION/ {found = 1} found && /minos/ {print $2; exit}')"
  if [[ "$recorded" != "$MIN_MACOS" ]]; then
    echo "$binary records LC_BUILD_VERSION minos ${recorded:-nothing}, expected $MIN_MACOS" >&2
    return 1
  fi
  echo "verified: $binary runs on macOS $MIN_MACOS or later"
}

platforms=()
assets=()
installer_layout="true"

for arch in $ARCHES; do
  case "$arch" in
    arm64|amd64) ;;
    *) echo "unsupported darwin architecture: $arch" >&2; exit 1 ;;
  esac
  platform="darwin-$arch"
  stage="$(mktemp -d)"
  app="$stage/$APP_NAME"
  mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"

  echo "building $EXECUTABLE for darwin/$arch (minimum macOS $MIN_MACOS)"
  # CGO_ENABLED=1 is what pulls in tray_darwin.m; -tags tray is what makes the embed,
  # the native shim and cmd/tunnelmesh-client-tray part of the build at all.
  #
  # The target has to be pinned for both halves of the link. MACOSX_DEPLOYMENT_TARGET
  # covers the Go-side objects and the clang driver acting as linker; CGO_CFLAGS and
  # CGO_LDFLAGS cover the .m translation units. Setting only one leaves the other half
  # recording the host version, which shows up as ld warnings about objects built for a
  # newer macOS and, on the runner, as an app nobody below the runner can open.
  (cd "$ROOT_DIR" && \
    CGO_ENABLED=1 GOOS=darwin GOARCH="$arch" \
    MACOSX_DEPLOYMENT_TARGET="$MIN_MACOS" \
    CGO_CFLAGS="${CGO_CFLAGS:-} -mmacosx-version-min=$MIN_MACOS" \
    CGO_LDFLAGS="${CGO_LDFLAGS:-} -mmacosx-version-min=$MIN_MACOS" \
    go build -tags tray -trimpath -ldflags="$LDFLAGS" \
    -o "$app/Contents/MacOS/$EXECUTABLE" "./cmd/tunnelmesh-client-tray")
  verify_deployment_target "$app/Contents/MacOS/$EXECUTABLE"

  sed "s/__VERSION__/${BUNDLE_VERSION}/g" "$INFO_TEMPLATE" > "$app/Contents/Info.plist"
  if [[ -f "$ICON_SOURCE" ]]; then
    cp "$ICON_SOURCE" "$app/Contents/Resources/AppIcon.icns"
  else
    # A CFBundleIconFile that points at nothing is worse than no icon key: Finder keeps
    # a stale cache entry for the missing name. Drop the key instead.
    /usr/libexec/PlistBuddy -c "Delete :CFBundleIconFile" "$app/Contents/Info.plist"
    echo "note: no icon at $ICON_SOURCE; packaging without one" >&2
  fi
  # The status-item glyph is optional in the same way: a bundle built without it falls
  # back to the system symbol, which is the pre-unification behaviour rather than a break.
  for glyph in TunnelMeshMenuBar.png "TunnelMeshMenuBar@2x.png" "TunnelMeshMenuBar@3x.png"; do
    if [[ -f "$MENUBAR_SOURCE_DIR/$glyph" ]]; then
      cp "$MENUBAR_SOURCE_DIR/$glyph" "$app/Contents/Resources/$glyph"
    else
      echo "note: $MENUBAR_SOURCE_DIR/$glyph is missing; the menu bar falls back to a system symbol" >&2
    fi
  done
  plutil -lint "$app/Contents/Info.plist" >/dev/null
  printf 'APPL????' > "$app/Contents/PkgInfo"

  # Apache-2.0 4(a) requires the license text to accompany every distributed copy and
  # 4(d) requires the NOTICE. Resources is where a bundle keeps that kind of file, and
  # it is inside the signature seal, so it cannot be swapped after signing.
  for legal in LICENSE NOTICE; do
    if [[ ! -f "$ROOT_DIR/$legal" ]]; then
      echo "$legal is missing from the repository root; refusing to package an unlicensed distribution" >&2
      exit 1
    fi
    cp "$ROOT_DIR/$legal" "$app/Contents/Resources/$legal"
  done

  echo "signing $APP_NAME (identity: $SIGN_IDENTITY)"
  codesign --force --sign "$SIGN_IDENTITY" "$app"
  codesign --verify --verbose=2 "$app"

  archive="tunnelmesh-client-tray-${VERSION}-${platform}.dmg"
  volume="$stage/volume"
  mkdir -p "$volume"
  # ditto rather than cp -R: it preserves the extended attributes and resource forks a
  # signed bundle carries, which a plain copy silently drops and thereby invalidates.
  ditto "$app" "$volume/$APP_NAME"
  # The alias is what turns the image into an installer: drag the app onto it and the copy
  # lands in /Applications with the right metadata.
  ln -s /Applications "$volume/Applications"
  if [[ -n "$DMG_BACKGROUND" ]]; then
    # Staged inside the volume, because the picture has to travel with the image: the alias
    # Finder records is volume relative, which is what makes it resolve on the machine that
    # mounts the published disk image rather than on the machine that built it.
    mkdir -p "$volume/.background"
    cp "$DMG_BACKGROUND" "$volume/.background/background.png"
  fi
  echo "creating $archive"
  create_disk_image "$volume" "$OUTPUT_DIR/$archive"
  # Verify the image we are about to publish, not the bundle we already verified: a
  # truncated or corrupt disk image passes every earlier check and only fails on the
  # operator's machine.
  hdiutil verify -quiet "$OUTPUT_DIR/$archive"

  # Signing the container is only meaningful with a real identity: that is the signature
  # notarytool submits and stapler staples. In ad-hoc mode the app inside is already
  # ad-hoc signed, so a second ad-hoc signature on the image would add nothing to verify.
  if [[ "$SIGN_IDENTITY" != "-" ]]; then
    codesign --force --sign "$SIGN_IDENTITY" "$OUTPUT_DIR/$archive"
    codesign --verify --verbose=2 "$OUTPUT_DIR/$archive"
  fi

  archive_hash="$(checksum "$OUTPUT_DIR/$archive" | awk '{print $1}')"
  printf '%s  %s\n' "$archive_hash" "$archive" >> "$OUTPUT_DIR/SHA256SUMS"

  platforms+=("\"darwin/${arch}\"")
  assets+=( "{\"platform\":\"${platform}\",\"archive\":\"${archive}\",\"extension\":\"dmg\",\"application\":\"${APP_NAME}\",\"volumeName\":\"${VOLUME_NAME}\",\"installerLayout\":${installer_layout}}" )
  rm -rf "$stage"
done

platform_json="$(IFS=,; printf '%s' "${platforms[*]}")"
asset_json="$(IFS=,; printf '%s' "${assets[*]}")"
cat > "$OUTPUT_DIR/manifest.json" <<EOF
{
  "version": "${VERSION}",
  "commit": "${COMMIT}",
  "buildTime": "${BUILD_TIME}",
  "bundleIdentifier": "${BUNDLE_ID}",
  "executable": "${EXECUTABLE}",
  "minimumMacOSVersion": "${MIN_MACOS}",
  "signingIdentity": "${SIGN_IDENTITY}",
  "notarized": false,
  "platforms": [${platform_json}],
  "assets": [${asset_json}],
  "checksums": "SHA256SUMS"
}
EOF

echo "tray artifacts written to $OUTPUT_DIR"
if [[ "$installer_layout" != "true" ]]; then
  echo "note: at least one disk image has no installer layout; manifest.json records it as \"installerLayout\": false" >&2
fi
if [[ "$SIGN_IDENTITY" == "-" ]]; then
  cat >&2 <<'NOTE'
note: the app is ad-hoc signed. It runs and registers its login item locally, but
Gatekeeper refuses a *downloaded* copy until it is allowed explicitly (System Settings >
Privacy & Security, or `xattr -d com.apple.quarantine`). The disk image itself is left
unsigned in this mode, which is why nothing here can be notarized. The login item is keyed
by the bundle's cdhash, so re-signing or moving the app invalidates it and the tray
reconciles the switch on next launch. Distributing through Gatekeeper needs a Developer ID
signature plus notarization; pass SIGN_IDENTITY="Developer ID Application: ..." to use one,
and the image will be signed with it too.
NOTE
fi
