package oidc

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// AuthRequest is one authorization redirect. State, Nonce, and CodeChallenge are
// generated by the caller and persisted in its own encrypted challenge row, so
// this package stays free of storage concerns.
type AuthRequest struct {
	State         string
	Nonce         string
	CodeChallenge string
	RedirectURI   string
	Scope         []string
}

// TokenResponse is the token endpoint result. Only the fields TunnelMesh acts on
// are decoded; a refresh token is intentionally discarded because console
// sessions are minted locally and never delegated back to the IdP.
type TokenResponse struct {
	IDToken     string
	AccessToken string
	TokenType   string
	ExpiresIn   time.Duration
}

// pkceVerifierBytes is 32 octets, the RFC 7636 recommended length, which yields
// a 43-character base64url verifier.
const pkceVerifierBytes = 32

// NewPKCE generates an S256 verifier and challenge pair. Plain PKCE is never
// offered: a plain challenge is the verifier itself, so anyone who can read the
// redirect can complete the exchange.
func NewPKCE() (verifier, challenge string, err error) {
	buf := make([]byte, pkceVerifierBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", "", fmt.Errorf("generate pkce verifier: %w", err)
	}
	verifier = base64.RawURLEncoding.EncodeToString(buf)
	sum := sha256.Sum256([]byte(verifier))
	return verifier, base64.RawURLEncoding.EncodeToString(sum[:]), nil
}

// randomURLToken generates a base64url value for state or nonce.
func randomURLToken(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// NewState returns a fresh authorization state value.
func NewState() (string, error) { return randomURLToken(24) }

// NewNonce returns a fresh id_token nonce value.
func NewNonce() (string, error) { return randomURLToken(24) }

// BuildAuthURL renders the authorization redirect. response_type is always
// "code" and code_challenge_method is always "S256"; neither is configurable,
// because both downgrades would silently weaken the flow.
func (rp *RelyingParty) BuildAuthURL(ctx context.Context, p Provider, req AuthRequest) (string, error) {
	endpoints, err := rp.Discover(ctx, p)
	if err != nil {
		return "", err
	}
	target, err := url.Parse(endpoints.Authorization)
	if err != nil {
		return "", errors.Join(ErrProviderInvalid, err)
	}
	if strings.TrimSpace(p.ClientID) == "" {
		return "", errors.Join(ErrProviderInvalid, errors.New("client id is required"))
	}
	if strings.TrimSpace(req.State) == "" || strings.TrimSpace(req.Nonce) == "" || strings.TrimSpace(req.CodeChallenge) == "" {
		return "", errors.Join(ErrProviderInvalid, errors.New("state, nonce, and code challenge are required"))
	}
	redirectURI := strings.TrimSpace(req.RedirectURI)
	if redirectURI == "" {
		redirectURI = strings.TrimSpace(p.RedirectURI)
	}
	if redirectURI == "" {
		return "", errors.Join(ErrProviderInvalid, errors.New("redirect uri is required"))
	}
	params := url.Values{}
	params.Set("response_type", "code")
	params.Set("client_id", p.ClientID)
	params.Set("redirect_uri", redirectURI)
	params.Set("scope", strings.Join(scopesFor(p, req.Scope), " "))
	params.Set("state", req.State)
	params.Set("nonce", req.Nonce)
	params.Set("code_challenge", req.CodeChallenge)
	params.Set("code_challenge_method", "S256")
	separator := "?"
	if target.RawQuery != "" {
		separator = "&"
	}
	return target.String() + separator + params.Encode(), nil
}

// scopesFor prefers the per-request scope list and falls back to the provider
// configuration, always keeping "openid" first.
func scopesFor(p Provider, override []string) []string {
	if len(override) > 0 {
		provider := Provider{Scopes: override}
		return provider.scopes()
	}
	return p.scopes()
}

// Exchange trades an authorization code for tokens. The request is form-encoded
// as the OAuth 2.0 token endpoint requires, and client authentication uses HTTP
// basic auth only when a secret exists, so public clients are not sent an empty
// credential that some IdPs reject.
func (rp *RelyingParty) Exchange(ctx context.Context, p Provider, code, verifier, redirectURI string) (TokenResponse, error) {
	endpoints, err := rp.Discover(ctx, p)
	if err != nil {
		return TokenResponse{}, err
	}
	secret, err := rp.clientSecret(ctx, p)
	if err != nil {
		return TokenResponse{}, err
	}
	if strings.TrimSpace(code) == "" {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, errors.New("code is required"))
	}
	if redirectURI == "" {
		redirectURI = p.RedirectURI
	}
	form := url.Values{}
	form.Set("grant_type", "authorization_code")
	form.Set("code", code)
	form.Set("redirect_uri", redirectURI)
	if verifier != "" {
		form.Set("code_verifier", verifier)
	}
	if secret == "" {
		// Without basic auth the client id must travel in the body.
		form.Set("client_id", p.ClientID)
	}

	requestCtx, cancel := context.WithTimeout(ctx, rp.cfg.HTTPTimeout)
	defer cancel()
	req, err := http.NewRequestWithContext(requestCtx, http.MethodPost, endpoints.Token, strings.NewReader(form.Encode()))
	if err != nil {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")
	if secret != "" {
		req.SetBasicAuth(p.ClientID, secret)
	}
	resp, err := rp.http.Do(req)
	if err != nil {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, rp.cfg.MaxBodyBytes+1))
	if err != nil {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, err)
	}
	if int64(len(body)) > rp.cfg.MaxBodyBytes {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, errResponseTooLarge)
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		// The IdP's error description is parsed for operator diagnostics but is
		// never echoed to the end user, and the response body is never included
		// verbatim because it may carry a token.
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, oauthError(resp.StatusCode, body))
	}
	var payload struct {
		IDToken     string `json:"id_token"`
		AccessToken string `json:"access_token"`
		TokenType   string `json:"token_type"`
		ExpiresIn   int64  `json:"expires_in"`
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, err)
	}
	if strings.TrimSpace(payload.IDToken) == "" {
		return TokenResponse{}, errors.Join(ErrTokenExchangeFailed, errors.New("id_token missing"))
	}
	return TokenResponse{
		IDToken:     payload.IDToken,
		AccessToken: payload.AccessToken,
		TokenType:   payload.TokenType,
		ExpiresIn:   time.Duration(payload.ExpiresIn) * time.Second,
	}, nil
}

// oauthError renders a non-2xx token response as a generic error carrying only
// the OAuth error code, never the description, the code, or the secret.
func oauthError(status int, body []byte) error {
	var payload struct {
		Error string `json:"error"`
	}
	if err := json.Unmarshal(body, &payload); err == nil && payload.Error != "" {
		return fmt.Errorf("token endpoint returned %s (status %d)", sanitizeOAuthErrorCode(payload.Error), status)
	}
	return fmt.Errorf("token endpoint status %d", status)
}

// sanitizeOAuthErrorCode keeps only a short token-shaped value so a hostile IdP
// cannot use this field to inject arbitrary text into an operator's log.
func sanitizeOAuthErrorCode(value string) string {
	value = strings.TrimSpace(value)
	if len(value) > 40 {
		value = value[:40]
	}
	out := make([]rune, 0, len(value))
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_', r == '-':
			out = append(out, r)
		default:
			out = append(out, '_')
		}
	}
	return string(out)
}
